import * as path from 'path';

import { IScaffoldingRepo } from '@/sdk/domain/ports/out/scaffolding-repo';
import { Result, ok, err } from '@/std';

const REGISTRY_RELATIVE_PATH = 'dev/ui/types/walde-cloud-api/index.d.ts';
const BARREL_RELATIVE_PATH = 'dev/cloud/src/apis/index.ts';

function buildRegistryContent(): string {
  return [
    `// Auto-managed by Walde. Do not edit this file manually. Last updated: ${new Date().toISOString()}`,
    "import type {} from '@walde.ai/sdk';",
    '',
    "declare module '@walde.ai/sdk' {",
    '  interface WaldeApiRegistry {}',
    '}',
    '',
  ].join('\n');
}

function buildBarrelContent(): string {
  return `// Auto-managed by Walde. Do not edit this file manually. Last updated: ${new Date().toISOString()}\n`;
}

export interface EnsureApiRegistryParams {
  targetPath: string;
}

/**
 * Ensures that both Walde-managed registry files exist within the project root:
 * - `dev/ui/types/walde-cloud-api/index.d.ts`: TypeScript typeRoots augmentation for the UI
 *   compilation. Auto-included by tsconfig (typeRoots + types) so no manual imports are needed.
 * - `dev/cloud/src/apis/index.ts`: Barrel export index for the cloud compilation.
 *
 * Called by both ScaffoldProjectWorkspace (during `walde init`) and
 * ScaffoldApi (during `walde api create`) so that both files are always
 * present regardless of which command runs first.
 */
export class EnsureApiRegistry {
  constructor(private readonly scaffoldingRepo: IScaffoldingRepo) {}

  async execute(params: EnsureApiRegistryParams): Promise<Result<void, string>> {
    try {
      const registryPath = path.join(params.targetPath, REGISTRY_RELATIVE_PATH);
      const barrelPath = path.join(params.targetPath, BARREL_RELATIVE_PATH);

      if (!(await this.scaffoldingRepo.fileExists(registryPath))) {
        await this.scaffoldingRepo.createDirectory(path.dirname(registryPath));
        await this.scaffoldingRepo.writeFile(registryPath, buildRegistryContent());
      }

      if (!(await this.scaffoldingRepo.fileExists(barrelPath))) {
        await this.scaffoldingRepo.createDirectory(path.dirname(barrelPath));
        await this.scaffoldingRepo.writeFile(barrelPath, buildBarrelContent());
      }

      return ok(undefined);
    } catch (error) {
      return err(error instanceof Error ? error.message : 'Failed to ensure API registry');
    }
  }
}
