import * as path from 'path';

import { IScaffoldingRepo } from '@/sdk/domain/ports/out/scaffolding-repo';
import { EnsureApiRegistry } from '@/sdk/domain/interactors/workspace/ensure-api-registry';
import { Result, ok, err } from '@/std';

const REGISTRY_RELATIVE_PATH = 'dev/ui/types/walde-cloud-api/index.d.ts';
const BARREL_RELATIVE_PATH = 'dev/cloud/src/apis/index.ts';

export interface ScaffoldApiParams {
  /** PascalCase class name, e.g. "MyApi" */
  name: string;
  /** Absolute path to the project root (the folder containing walde.json) */
  targetPath: string;
}

function waldeTimestamp(): string {
  return new Date().toISOString();
}

/**
 * Derives the three canonical name forms from a PascalCase API name.
 */
function deriveNames(pascal: string): { pascal: string; kebab: string; camel: string } {
  const kebab = pascal
    .replace(/([A-Z])/g, (match, char, offset) => (offset === 0 ? char.toLowerCase() : `-${char.toLowerCase()}`))
    .replace(/^-/, '');
  const camel = pascal.charAt(0).toLowerCase() + pascal.slice(1);
  return { pascal, kebab, camel };
}

function buildContractsContent(pascal: string, kebab: string): string {
  return [
    `// ${kebab}.ts — contracts for ${pascal}`,
    `// TODO: define the input fields for ${pascal}`,
    `export interface ${pascal}Input {}`,
    '',
    `// TODO: define the output fields for ${pascal}`,
    `export interface ${pascal}Output {}`,
    '',
  ].join('\n');
}

function buildHandlerContent(pascal: string, kebab: string): string {
  return [
    "import { WaldeApi } from '@walde.ai/sdk';",
    `import type { ${pascal}Input, ${pascal}Output } from '../contracts/${kebab}';`,
    '',
    `export class ${pascal} extends WaldeApi<${pascal}Input, ${pascal}Output> {`,
    `  async handler(_input: ${pascal}Input): Promise<${pascal}Output> {`,
    `    throw new Error('Not implemented');`,
    '  }',
    '}',
    '',
  ].join('\n');
}

/**
 * Parses the existing registry file content and extracts all registered camelCase keys.
 */
function parseRegisteredKeys(content: string): Set<string> {
  const keys = new Set<string>();
  const lineRegex = /^\s+(\w+):\s*\{/gm;
  let match;
  while ((match = lineRegex.exec(content)) !== null) {
    keys.add(match[1]);
  }
  return keys;
}

/**
 * Rewrites the typeRoots registry file to include a new entry for the given API.
 *
 * The file lives at `dev/ui/types/walde-cloud-api/index.d.ts`. It is a TypeScript
 * module (imports `@walde.ai/sdk`) so that `declare module '@walde.ai/sdk'` is
 * treated as an augmentation. The `typeRoots` + `types` settings in the UI tsconfig
 * cause TypeScript to auto-include this file globally — no manual import needed.
 *
 * Template structure:
 * ```ts
 * // Auto-managed by Walde. Do not edit this file manually. Last updated: <ISO>
 * import type {} from '@walde.ai/sdk';
 * import type { FooInput, FooOutput } from '../../cloud/src/contracts/foo';
 *
 * declare module '@walde.ai/sdk' {
 *   interface WaldeApiRegistry {
 *     foo: { input: FooInput; output: FooOutput };
 *   }
 * }
 * ```
 */
function addEntryToRegistry(existing: string, pascal: string, kebab: string, camel: string): string {
  // Import path is relative from dev/ui/types/walde-cloud-api/ to dev/cloud/src/contracts/
  const importLine = `import type { ${pascal}Input, ${pascal}Output } from '../../cloud/src/contracts/${kebab}';`;
  const entryLine = `    ${camel}: { input: ${pascal}Input; output: ${pascal}Output };`;

  let updated = existing;

  // Refresh the "Last updated" timestamp in the header
  updated = updated.replace(
    /^\/\/ Auto-managed by Walde\..*$/m,
    `// Auto-managed by Walde. Do not edit this file manually. Last updated: ${waldeTimestamp()}`
  );

  // Insert import before the `declare module` line
  const declareIndex = updated.indexOf("declare module '@walde.ai/sdk'");
  if (declareIndex === -1) {
    return updated; // malformed file; do not corrupt it
  }
  updated = updated.slice(0, declareIndex) + importLine + '\n' + updated.slice(declareIndex);
  // Ensure exactly one blank line between the import block and declare module
  updated = updated.replace(/\n+declare module '@walde\.ai\/sdk'/, "\n\ndeclare module '@walde.ai/sdk'");

  // Insert entry inside the interface block
  const interfaceClosePattern = /(\s*interface WaldeApiRegistry \{)([^}]*)(\})/s;
  updated = updated.replace(interfaceClosePattern, (_match, open, body, close) => {
    return `${open}${body}${entryLine}\n  ${close}`;
  });

  return updated;
}

/**
 * Appends a barrel export to `dev/cloud/src/apis/index.ts` and refreshes the timestamp.
 */
function addBarrelExport(existing: string, pascal: string, kebab: string): string {
  const updated = existing.replace(
    /^\/\/ Auto-managed by Walde\..*$/m,
    `// Auto-managed by Walde. Do not edit this file manually. Last updated: ${waldeTimestamp()}`
  );
  const exportLine = `export { ${pascal} } from './${kebab}';`;
  return updated.trimEnd() + '\n' + exportLine + '\n';
}

/**
 * Scaffolds a new API endpoint in the user's Walde project.
 *
 * Creates:
 * 1. `dev/cloud/src/contracts/<kebab>.ts` — empty input/output interfaces
 * 2. `dev/cloud/src/apis/<kebab>.ts` — WaldeApi subclass stub
 * 3. `dev/cloud/src/apis/index.ts` — updated barrel export (Walde-managed)
 * 4. `dev/ui/types/walde-cloud-api/index.d.ts` — updated typeRoots augmentation (Walde-managed)
 */
export class ScaffoldApi {
  private readonly ensureApiRegistry: EnsureApiRegistry;

  constructor(private readonly scaffoldingRepo: IScaffoldingRepo) {
    this.ensureApiRegistry = new EnsureApiRegistry(scaffoldingRepo);
  }

  async execute(params: ScaffoldApiParams): Promise<Result<void, string>> {
    try {
      const { pascal, kebab, camel } = deriveNames(params.name);

      const registryResult = await this.ensureApiRegistry.execute({ targetPath: params.targetPath });
      if (registryResult.isErr()) {
        return err(registryResult.unwrapErr());
      }

      const registryPath = path.join(params.targetPath, REGISTRY_RELATIVE_PATH);
      const registryContent = await this.scaffoldingRepo.readFile(registryPath);
      const existingKeys = parseRegisteredKeys(registryContent);

      if (existingKeys.has(camel)) {
        return err(
          `An API named '${camel}' already exists in WaldeApiRegistry. ` +
            `Choose a different --name or edit the existing handler.`
        );
      }

      const contractsPath = path.join(params.targetPath, `dev/cloud/src/contracts/${kebab}.ts`);
      await this.scaffoldingRepo.createDirectory(path.dirname(contractsPath));
      await this.scaffoldingRepo.writeFile(contractsPath, buildContractsContent(pascal, kebab));

      const handlerPath = path.join(params.targetPath, `dev/cloud/src/apis/${kebab}.ts`);
      await this.scaffoldingRepo.createDirectory(path.dirname(handlerPath));
      await this.scaffoldingRepo.writeFile(handlerPath, buildHandlerContent(pascal, kebab));

      const updatedRegistry = addEntryToRegistry(registryContent, pascal, kebab, camel);
      await this.scaffoldingRepo.writeFile(registryPath, updatedRegistry);

      const barrelPath = path.join(params.targetPath, BARREL_RELATIVE_PATH);
      const barrelContent = await this.scaffoldingRepo.readFile(barrelPath);
      await this.scaffoldingRepo.writeFile(barrelPath, addBarrelExport(barrelContent, pascal, kebab));

      return ok(undefined);
    } catch (error) {
      return err(error instanceof Error ? error.message : 'Failed to scaffold API');
    }
  }
}
